doctrine:
    dbal:
        dbname:   '%env(resolve:DB_NAME)%'
        host:     '%env(resolve:DB_HOST)%'
        port:     '%env(resolve:DB_PORT)%'
        user:     '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PASSWORD)%'
        driver: pdo_mysql

        # IMPORTANT: You MUST configure your server version,
        server_version: '8.0'

        # only needed for MySQL
        charset: utf8mb4
        default_table_options:
            collate: utf8mb4_unicode_ci

        types:
            milliseconds_dt: App\Doctrine\DBAL\Type\MillisecondsDateTime
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/App/Entity'
                prefix: 'App\Entity'
                alias: App
