monolog:
    channels:
        - telegram
        - deprecation

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: [ "!event" ]
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine", "!console" ]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                channels: [ "!event" ]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                buffer_size: 50
                excluded_http_codes: [404, 405]
                channels: [ '!telegram' ]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            telegram:
                type: rotating_file
                max_files: 10
                path: "%kernel.logs_dir%/telegram.log"
                level: debug
                channels: [ 'telegram' ]
            deprecation:
                type: stream
                channels: [ deprecation ]
                path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
