version: '2'
services:
    hedgehog:
        build:
            context: ./docker/db
            args:
                HOST_UID: ${HOST_UID}
        volumes:
            - ./var/db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_DATABASE: mttblog
            MYSQL_USER: mttblog
            MYSQL_PASSWORD: docker

    rhinoceros:
        build:
            context: ./docker/web
            # dockerfile: prod/Dockerfile
            args:
                HOST_UID: ${HOST_UID}
        volumes:
            - .:/var/www/html
        ports:
            - "80:80"
        links:
            - hedgehog
            - mailcatcher
        depends_on:
            - hedgehog
            - mailcatcher

    ape:
        build: ./docker/dbadmin
        ports:
            - "8088:80"
        links:
            - hedgehog
        depends_on:
            - hedgehog
        environment:
            PMA_HOST: hedgehog
            PMA_USER: root
            PMA_PASSWORD: docker

    mailcatcher:
        image: xelbot/mailcatcher
        ports:
            - "1080:1080"
