version: '2'
services:
    hedgehog:
        build:
            context: ./docker/db
            args:
                HOST_UID: ${HOST_UID}
        volumes:
            - ./var/db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_DATABASE: mttblog
            MYSQL_USER: mttblog
            MYSQL_PASSWORD: docker

    rhinoceros:
        build:
            context: ./docker/web
            # dockerfile: prod/Dockerfile
            args:
                HOST_UID: ${HOST_UID}
        hostname: "rhinoceros"
        container_name: "rhinoceros"
        volumes:
            - .:/var/www/html
            - ${UPLOADS_PATH}:/var/www/resources
        ports:
            - "8033:80"
        links:
            - hedgehog
            - mailcatcher
        depends_on:
            - hedgehog
            - mailcatcher
        environment:
            APPLICATION_ENV: development

    mailcatcher:
        image: xelbot/mailcatcher
        ports:
            - "1080:1080"

    sloth:
        build: ./docker/nginx
        volumes:
            - ./web:/usr/share/nginx/html
            - ${UPLOADS_PATH}:/var/www/resources
        ports:
            - "443:443"
            - "80:80"
        depends_on:
            - rhinoceros
        links:
            - rhinoceros
