version: '2'
services:
    source:
        image: alpine:3.6
        volumes:
            - .:/var/www/html
            - ${UPLOADS_PATH}:/var/www/resources

    hedgehog:
        build:
            context: ./docker/db
            args:
                HOST_UID: ${HOST_UID}
        container_name: "hedgehog_mysql"
        volumes:
            - ${DB_DATA_PATH}:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_DATABASE: mttblog
            MYSQL_USER: mttblog
            MYSQL_PASSWORD: docker

    rhinoceros:
        build:
            context: ./docker/web
            # dockerfile: prod/Dockerfile
            args:
                HOST_UID: ${HOST_UID}
        hostname: "rhinoceros"
        container_name: "rhinoceros"
        volumes_from:
            - source
        volumes:
            - ./docker/web/apache_${APP_ENV}.conf:/etc/apache2/sites-available/000-default.conf:ro
        ports:
            - "8033:80"
        links:
            - hedgehog
            - mailcatcher
        depends_on:
            - hedgehog
            - mailcatcher
            - source
        environment:
            APPLICATION_ENV: development
            CIRCLE_ARTIFACTS: /var/www/html/var/tests

    mailcatcher:
        image: xelbot/mailcatcher
        ports:
            - "1080:1080"

    nodejs:
        build: ./docker/nodejs
        volumes_from:
            - source
        depends_on:
            - source

    sloth:
        build: ./docker/nginx
        volumes_from:
            - source
        ports:
            - "443:443"
            - "80:80"
        depends_on:
            - rhinoceros
        links:
            - rhinoceros
