services:
    rhinoceros:
        build:
            context: ./docker/web
            # dockerfile: prod/Dockerfile
            args:
                HOST_UID: ${HOST_UID}
        platform: linux/amd64
        hostname: "rhinoceros"
        container_name: "rhinoceros"
        volumes:
            - .:/var/www/html
            - ./docker/web/apache.conf:/etc/apache2/sites-available/000-default.conf:ro
            - ${UPLOADS_PATH}:/var/www/resources
            - app-logs:/var/www/html/var/log
        tmpfs:
            - /tmp
            - /var/www/html/var/cache:uid=${HOST_UID},gid=${HOST_UID}
            - /var/www/html/var/spool:uid=${HOST_UID},gid=${HOST_UID}
        ports:
            - "8033:80"
        links:
            - mailpit
        depends_on:
            - mailpit
        environment:
            APPLICATION_ENV: development
            CIRCLE_ARTIFACTS: /var/www/html/var/tests
            VARNISH_BAN_TOKEN: ${VARNISH_BAN_TOKEN}
        extra_hosts:
            - "database.lan:${DATABASE_IP}"
            - "reprogl.xelbot.com:${APPLICATION_IP}"
        networks:
            - blognet

    mailpit:
        image: axllent/mailpit
        container_name: "mailpit"
        ports:
            - "8025:8025"
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
            TZ: "Europe/Moscow"
        extra_hosts:
            - "reprogl.xelbot.com:${APPLICATION_IP}"
        networks:
            - blognet

    nodejs:
        image: xelbot/docker-zendblog-nodejs
        platform: linux/amd64
        volumes:
            - .:/var/www/html
        networks:
            - blognet

    sloth:
        build: ./docker/nginx
        container_name: "sloth"
        platform: linux/amd64
        volumes:
            - .:/var/www/html
            - ${GOLANG_BLOG_PATH}:/var/www/app
        ports:
            - "443:443"
            - "80:80"
        depends_on:
            - rhinoceros
        links:
            - rhinoceros
        networks:
            - blognet

    newt:
        image: busybox
        container_name: newt
        platform: linux/amd64
        volumes:
            - app-logs:/var/log/zendblog
        command: [ "tail", "-f", "/var/log/zendblog/dev.log" ]
        depends_on:
            - rhinoceros

networks:
    blognet:
        external: true

volumes:
    app-logs:
