api_root:
    path: /api
    defaults:
        _controller: FrameworkBundle:Template:template
        template: "MttBlogBundle:default:api.html.twig"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

logout:
    path: /logout

login_check:
    path: /login_check
