imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        browsertitle:   "%browsertitle%"
        image_basepath: "%image_basepath%"
        frontend_site:  "%frontend_site%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ MttBlogBundle, MttUserBundle ]
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: "%nodemodules_bin_path%/uglifyjs"
        uglifycss:
            bin: "%nodemodules_bin_path%/uglifycss"
    assets:
        jquery_ui_base:
            inputs:
                - 'bundles/mttblog/components/jquery-ui/themes/base/core.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/accordion.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/autocomplete.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/button.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/datepicker.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/dialog.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/draggable.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/menu.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/progressbar.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/resizable.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/selectable.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/selectmenu.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/sortable.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/slider.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/spinner.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/tabs.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/tooltip.css'
                - 'bundles/mttblog/components/jquery-ui/themes/base/theme.css'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        schema_filter: "~^(?!v_)~"

    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: "KnpPaginatorBundle:Pagination:sliding.html.twig"     # sliding pagination controls template
        sortable: "KnpPaginatorBundle:Pagination:sortable_link.html.twig" # sort link template

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    encryption: "%mailer_encryption%"
    spool:      { type: memory }

parameters:
    disqus:
        shortname: "%disqus_shortname%"
        secret_key: "%disqus_secret_key%"
        owner_id: "%disqus_owner_id%"

services:
    _defaults:
        autowire: false
        autoconfigure: false
