imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    container.autowiring.strict_mode: false

framework:
    #esi:             ~
    translator:      { fallback: "ru" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

sensio_framework_extra:
    router:
        annotations: false

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        browsertitle:   "%browsertitle%"
        frontend_site:  "%frontend_site%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        schema_filter: "~^(?!v_)~"
        types:
            milliseconds_dt: Mtt\BlogBundle\Doctrine\DBAL\Type\MillisecondsDateTime
        server_version: "8.0"

    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: "KnpPaginatorBundle:Pagination:sliding.html.twig"     # sliding pagination controls template
        sortable: "KnpPaginatorBundle:Pagination:sortable_link.html.twig" # sort link template

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    encryption: "%mailer_encryption%"
    spool:      { type: memory }
