mtt_blog:
    resource: "@MttBlogBundle/Controller/"
    type:     annotation
    prefix:   /

mtt_user:
    resource: "@MttUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

logout:
    path: /logout

logincheck:
    path: /login_check
