mtt_blog:
    resource: "@MttBlogBundle/Controller/"
    type:     annotation
    prefix:   /

mtt_user:
    resource: "@MttUserBundle/Controller/"
    type:     annotation
    prefix:   /

api_root:
    path: /api
    defaults:
        _controller: FrameworkBundle:Template:template
        template: "MttBlogBundle:default:api.html.twig"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

logout:
    path: /logout

logincheck:
    path: /login_check
