security:
    encoders:
        Mtt\UserBundle\Entity\User:
            algorithm: sha384
            iterations: 1
            encode_as_base64: false

    providers:
        user_db:
            entity:
                class: Mtt\UserBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
