POST {{base_url}}/telegram/{{telegram_webhook_token}}
Accept: application/json

###

POST {{base_url}}/telegram/{{telegram_webhook_token}}
Accept: application/json
Content-Type: application/json

{
    "update_id":999373967,
    "message":{
        "message_id":1906,
        "from":{
            "id":444486199,"is_bot":false,"first_name":"Alexander","last_name":"Harchenko",
            "username":"morontt","language_code":"ru"
        },
        "chat":{
            "id":444486199,"first_name":"Alexander","last_name":"Harchenko",
            "username":"morontt","type":"private"
        },
        "date":1647771298,
        "text":"/deletecomment 489",
        "entities":[
            {"offset":0,"length":14,"type":"bot_command"}
        ]
    }
}

###

POST {{base_url}}/telegram/{{telegram_webhook_token}}
Accept: application/json
Content-Type: application/json

{
    "update_id": 999398967,
    "message": {
        "message_id": 2655,
        "from": {
            "id": 444486199,
            "is_bot": false,
            "first_name": "Alexander",
            "last_name": "Harchenko",
            "username": "morontt",
            "language_code": "ru"
        },
        "chat": {
            "id": 444486199,
            "first_name": "Alexander",
            "last_name": "Harchenko",
            "username": "morontt",
            "type": "private"
        },
        "date": 1687204395,
        "text": "/answer 552\nДа, были времена, приходилось программировать по книжкам\n\nИ не только...\n",
        "entities": [
            {
                "offset": 0,
                "length": 7,
                "type": "bot_command"
            }
        ]
    }
}

###

POST {{base_url}}/telegram/{{telegram_webhook_token}}
Accept: application/json
Content-Type: application/json

{
    "update_id": 657374014,
    "message": {
        "message_id": 2681,
        "from":{
            "id": 5465693906,"is_bot":false,"first_name":"Alexander","last_name":"Dublikatov","language_code":"ru"},
        "chat":{
            "id": 5465693906,"first_name":"Alexander","last_name":"Dublikatov","type":"private"},
        "date": 1687246559,
        "text":"/start",
        "entities":[{"offset":0,"length":6,"type":"bot_command"}]
    }
}
