<?php

namespace Mtt\BlogBundle\Entity\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends BaseRepository
{
    /**
     * @return array
     */
    public function getNamesArray()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c.id', 'c.name')
            ->orderBy('c.name', 'ASC');

        return $qb->getQuery()->getArrayResult();
    }
}
