<?php

namespace Mtt\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Mtt\BlogBundle\Entity\GeoLocationCountry;

/**
 * GeoLocationCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method GeoLocationCountry|null findOneByCode($code)
 */
class GeoLocationCountryRepository extends EntityRepository
{
}
