<?php

namespace Mtt\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Mtt\BlogBundle\Entity\GeoLocation;

/**
 * GeoLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method GeoLocation|null findOneByIpAddress($ip)
 */
class GeoLocationRepository extends EntityRepository
{
}
