<?php

namespace Mtt\BlogBundle\Entity\Repository;

/**
 * MediaFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaFileRepository extends BaseRepository
{
    /**
     * @param int $postId
     *
     * @return \Mtt\BlogBundle\Entity\MediaFile[]
     */
    public function getFilesByPost($postId)
    {
        $qb = $this->createQueryBuilder('m');

        $qb
            ->where($qb->expr()->eq('m.post', ':postId'))
            ->setParameter('postId', $postId)
            ->orderBy('m.id')
        ;

        return $qb->getQuery()->getResult();
    }

    /**
     * @param int $postId
     *
     * @return int
     */
    public function getCountByPostId($postId)
    {
        $qb = $this->createQueryBuilder('m');

        $qb
            ->select('COUNT(m.id)')
            ->where($qb->expr()->eq('m.post', ':postId'))
            ->setParameter('postId', $postId)
        ;

        return (int)$qb->getQuery()->getSingleScalarResult();
    }

    /**
     * @return \Mtt\BlogBundle\Entity\MediaFile[]
     */
    public function getNotBackuped()
    {
        $qb = $this->createQueryBuilder('m');

        $qb
            ->where($qb->expr()->eq('m.backuped', ':backuped'))
            ->setParameter('backuped', false)
            ->setMaxResults(30)
        ;

        return $qb->getQuery()->getResult();
    }
}
