<?php

namespace Mtt\BlogBundle\Entity\Repository;

/**
 * MediaFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaFileRepository extends BaseRepository
{
}
