<?php

namespace Mtt\BlogBundle\Entity\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends BaseRepository
{
}
