<?php

namespace Mtt\BlogBundle\Entity\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use Mtt\BlogBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends ServiceEntityRepository
{
    const ITERATION_STEP = 15;

    use ListQueryTrait;

    /**
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Post::class);
    }

    /**
     * @param int $i
     *
     * @return Post[]
     */
    public function getPostsForIteration($i)
    {
        $qb = $this->createQueryBuilder('p');

        $qb
            ->orderBy('p.id')
            ->setFirstResult($i * self::ITERATION_STEP)
            ->setMaxResults(self::ITERATION_STEP)
        ;

        return $qb->getQuery()->getResult();
    }
}
