<?php

namespace Mtt\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Mtt\BlogBundle\Entity\SystemParameters;

/**
 * SystemParametersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method SystemParameters|null findOneByOptionKey($key)
 */
class SystemParametersRepository extends EntityRepository
{
}
