<?php

namespace Mtt\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Mtt\BlogBundle\Entity\Tag;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    /**
     * @return \Doctrine\ORM\Query
     */
    public function getListQuery()
    {
        $qb = $this->createQueryBuilder('t')
            ->orderBy('t.name', 'ASC');

        return $qb->getQuery();
    }

    /**
     * @param $term
     * @return Tag[]
     */
    public function getForAutocomplete($term)
    {
        $qb = $this->createQueryBuilder('t');

        if ($term) {
            $qb
                ->andWhere($qb->expr()->like('t.name', ':name'))
                ->setParameter('name', '%' . $term . '%')
            ;
        }

        $qb
            ->orderBy('t.name')
            ->setMaxResults(10)
        ;

        return $qb->getQuery()->getResult();
    }
}
