<?php

namespace Mtt\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrackingArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackingArchiveRepository extends EntityRepository
{
}
