monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            buffer_size: 50
            channels: ['!telegram']
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        telegram:
            type: rotating_file
            max_files: 10
            path: "%kernel.logs_dir%/telegram.log"
            level: debug
            channels: ['telegram']
        console:
            type: console
            process_psr_3_messages: false
