services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mtt\UserBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Security/Authentication/Token,OAuth/Providers,Event}'

    Mtt\UserBundle\Entity\Repository\:
        resource: '../../Entity/Repository'
        tags: ['doctrine.repository_service']

    Mtt\UserBundle\EventListener\AvatarListener:
        tags:
            - { name: kernel.event_listener, event: mtt_user.external_user.created, method: onCreate }

    Mtt\UserBundle\EventListener\LoginListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }
