services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mtt\UserBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Security/Authentication/Token,OAuth/Providers,Event}'

    Mtt\UserBundle\Entity\Repository\:
        resource: '../../Entity/Repository'
        tags: ['doctrine.repository_service']
