services:
    mtt_blog.json_body_listener:
        class: Mtt\BlogBundle\EventListener\JsonBodyListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10 }

    mtt_blog.api.data_converter:
        class: Mtt\BlogBundle\API\DataConverter
        arguments: [ @doctrine ]

    mtt_blog.cron_chain:
        class: Mtt\BlogBundle\Cron\CronChain
