services:
    mtt_blog.json_body_listener:
        class: Mtt\BlogBundle\EventListener\JsonBodyListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10 }
