services:
    mtt_blog.json_body_listener:
        class: Mtt\BlogBundle\EventListener\JsonBodyListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10 }

    mtt_blog.ignore_tables_listener:
        class: Mtt\BlogBundle\EventListener\IgnoreTablesListener
        tags:
            - {name: doctrine.event_listener, event: postGenerateSchema }

    mtt_blog.api.data_converter:
        class: Mtt\BlogBundle\API\DataConverter
        arguments: [ "@doctrine.orm.entity_manager", "@mtt_blog.text_processor" ]

    mtt_blog.ip_info:
        class: Mtt\BlogBundle\Service\IpInfo
        arguments: [ "@doctrine.orm.entity_manager", "%ipinfodb_key%" ]

    mtt_blog.cron_chain:
        class: Mtt\BlogBundle\Cron\CronChain

    mtt_blog.db_backup:
        class: Mtt\BlogBundle\Cron\Daily\DatabaseBackup
        arguments:
            - "%database_name%"
            - "%database_user%"
            - "%database_password%"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: cron-daily }

    mtt_blog.images_backup:
        class: Mtt\BlogBundle\Cron\Daily\ImagesBackup
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: cron-daily }

    mtt_blog.disqus_grabber:
        class: Mtt\BlogBundle\Cron\Daily\DisqusGrabber
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%disqus%"
            - "%admin_email%"
        tags:
            - { name: cron-daily }

    mtt_blog.geolocation_cron:
        class: Mtt\BlogBundle\Cron\Daily\CommentGeoLocation
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@mtt_blog.ip_info"
        tags:
            - { name: cron-daily }

    mtt_blog.image_manager:
        class: Mtt\BlogBundle\Service\ImageManager
        arguments: [ "@doctrine.orm.entity_manager" ]

    mtt_blog.text_processor:
        class: Mtt\BlogBundle\Service\TextProcessor
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%image_basepath%"
