parameters:
#    mtt_blog.example.class: Mtt\BlogBundle\Example

services:
#    mtt_blog.example:
#        class: %mtt_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
