services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $dropboxKey: "%dropbox_key%"
            $dropboxSecret: "%dropbox_secret%"

    Mtt\BlogBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Model,Event,OAuth2,Utils,Service/IpInfo/LocationInfo.php,Doctrine/DBAL,DTO,Form}'

    Mtt\BlogBundle\Entity\Repository\:
        resource: '../../Entity/Repository'
        tags: ['doctrine.repository_service']

    Mtt\BlogBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
