services:
    mtt_blog.json_body_listener:
        class: Mtt\BlogBundle\EventListener\JsonBodyListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10 }

    mtt_blog.api.data_converter:
        class: Mtt\BlogBundle\API\DataConverter
        arguments: [ "@doctrine.orm.entity_manager", "@mtt_blog.text_processor" ]

    mtt_blog.cron_chain:
        class: Mtt\BlogBundle\Cron\CronChain

    mtt_blog.db_backup:
        class: Mtt\BlogBundle\Cron\Daily\DatabaseBackup
        arguments:
            - "%database_name%"
            - "%database_user%"
            - "%database_password%"
            - "@doctrine"
        tags:
            - { name: cron-daily }

    mtt_blog.images_backup:
        class: Mtt\BlogBundle\Cron\Daily\ImagesBackup
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%amazon_s3%"
        tags:
            - { name: cron-daily }

    mtt_blog.image_manager:
        class: Mtt\BlogBundle\Service\ImageManager
        arguments: [ "%amazon_s3%", "@doctrine.orm.entity_manager" ]

    mtt_blog.text_processor:
        class: Mtt\BlogBundle\Service\TextProcessor
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%image_basepath%"
